### PR TITLE
Rework disguise functionality and appearance

### PR DESCRIPTION
**Pull request by cannonfodder1**
#101 
- [x] Remove weapon infil multipliers
- [x] Add watchtower immunity
- [x] Change T2 disguise to be actual ADVENT armor
- [ ] Use crysis nanosuit models for T3 disguise

### CODE REVIEW

**Comment by Xymanek** [comment]
Why is `X2Item_InfiltrationSchematics` back?

**Comment by cannonfodder1** [comment]
Because it was in my x2proj but not actually in the file, and I couldn’t find where the armour costs or the tech requirements were located. Thus, I assumed that the schematic file was supposed to be there after all.

**Comment by cannonfodder1** [comment]
Update on the nanosuit visuals: Kexx is in discussion with his project partner to see if he can release the models for our use. Other than that, this PR is functionally ready to go. If the visuals aren't available by Alpha1.1 then just merge this as is and we can update it later.

**Comment by Xymanek** [comment]
image
image

Also, I generally do not understand what you are trying to do with the looks rework... DId I miss something in chat?

**Comment by Xymanek** [comment]
You will also need to remove references to civilian detection immunity from loc files

**Pull request merged**
