### PR TITLE
Enable gather intel and gather supplies

### LINKED ISSUE #291: GatherSupplies and GatherIntel chains cannot spawn
They are not marked in deck and nothing in code spawns them directly

Additionally, I propose locking Supply Raid only to regions with radio relay built, to prevent it from showing up early (rewards too good)

### PR DESCRIPTION
**Pull request by cannonfodder1**
Closes #291 except for the supply raid issue which is as of yet undecided

### CODE REVIEW

**Comment by Xymanek** [comment]
I don't understand why limit it only if player has below X resources

**Comment by cannonfodder1** [comment]
That was the original idea for these. They're assaults, so they are much easier and just as rewarding as Informant/SupplyRaid chains. They were intended to help the player out if they were in a resource pinch.

**Comment by Xymanek** [comment]
`Reward_Intel`: 80/90 +-20%. Therefore 64-96/72-108

**Comment by Xymanek** [comment]
Values for gather supplies: https://docs.google.com/spreadsheets/d/1qeFskR_o7NmkwvIk3FmSxEciDlAqqgtT_FPkdEf7SM8/edit#gid=0

Will add supply raid and ufo later there

**Comment by Xymanek** [comment]
Can you get rid of basically everything from first commit? Since we no longer use "max xcom hq resource count" condition

**Comment by cannonfodder1** [comment]
For github history: we've decided to make the assault chains the basic versions of the more complex supply raid and capture informant chains. These advanced chains include facility and UFO chains, and can only spawn in regions that the player has built a radio relay in.

**Pull request merged**
