### PR TITLE
Merge item-infil-modifiers into master branch

### PR DESCRIPTION
**Pull request by cannonfodder1**
(Ignore the changes to UIEventQueue_MultipleActions, that's already been tested and committed to master branch.)

### CODE REVIEW

**Comment by Xymanek** [comment]
Ok, so here is how I see this should be implemented (via templates):

* We make a new template class, `class CI_ItemInfiltrationModTemplate extends X2DataTemplate`
* We make a new template manager `class CI_ItemInfiltrationModTemplateManager extends X2DataTemplateManager`
* We make a new data set class `class CI_ItemInfiltrationMod extends X2DataSet`
* We make `class CI_ItemInfiltrationMod_DefaultSet extends CI_ItemInfiltrationMod` where we will define all our own modifiers for items

Note that you will need to look in base game files (`X2DataTemplate` and so forth) on how to properly create new type of templates, but it's documented pretty good there

**Now, why templates?**

* Templates are faster to look up rather than searching array of structs every time
* Templates are objects, which means that they are nullable (can be `none`) - if we don't want some item to affect infiltration duration, then we just do not create a template for it
* Templates are objects, meaning that unlike structs they are not duplicated every time you pass them from function to function (which is faster, especially the more fields there are)
* Other mods can OPTC to modify the infiltration modifiers in a very easy manner

**Comment by Xymanek** [comment]
Also, I suggest you to create a new branch (and new pull request) since this one is pretty messy now

**Comment by Xymanek** [comment]
@robojumper can you also please take a look at my suggestions above? Maybe I missed something?

**Comment by robojumper** [comment]
Why does this PR remove UIEventQueue_MultipleActions? Merging this would remove the file from master.

**Comment by cannonfodder1** [comment]
Roger that on all of this. Deleting this branch/PR.

**Pull request closed without merging**
